apiVersion: v1
kind: List
metadata:
  name: managedset-controller-list
  annotations:
    version: "{{TRAVIS_COMMIT}}"
type: array
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: managedset-controller
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: managedset-controller
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: managedset-controller
          name: managedset-controller
        spec:
          serviceAccountName: razeedeploy-sa
          containers:
          - image: "quay.io/razee/managedset:{{TRAVIS_TAG}}"
            resources:
              limits:
                memory: 200Mi
                cpu: 100m
              requests:
                memory: 75Mi
                cpu: 40m
            imagePullPolicy: Always
            name: managedset-controller
            livenessProbe:
              exec:
                command:
                - sh/liveness.sh
              initialDelaySeconds: 30
              periodSeconds: 150
              timeoutSeconds: 30
              failureThreshold: 1
            volumeMounts:
            - mountPath: /usr/src/app/config
              name: razeedeploy-config
          volumes:
          - name: razeedeploy-config
            configMap:
              name: razeedeploy-config
              defaultMode: 420
              optional: true

  - apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      # name must match the spec fields below, and be in the form: <plural>.<group>
      name: managedsets.deploy.razee.io
    spec:
      # group name to use for REST API: /apis/<group>/<version>
      group: deploy.razee.io
      # list of versions supported by this CustomResourceDefinition
      versions:
        - name: v1alpha1
          # Each version can be enabled/disabled by Served flag.
          served: true
          # One and only one version must be marked as the storage version.
          storage: true
      # either Namespaced or Cluster
      scope: Namespaced
      names:
        # plural name to be used in the URL: /apis/<group>/<version>/<plural>
        plural: managedsets
        # singular name to be used as an alias on the CLI and for display
        singular: managedset
        # kind is normally the CamelCased singular type. Your resource manifests use this.
        kind: ManagedSet
        # shortNames allow shorter string to match your resource on the CLI
        shortNames:
        - ms
      subresources:
        # status enables the status subresource.
        status: {}
      validation:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          properties:
            spec:
              type: object
              required: [resources]
              properties:
                resources:
                  type: array
                  items:
                    type: object
                    required: [kind, apiVersion, metadata]
                    properties:
                      kind:
                        type: string
                      apiVersion:
                        type: string
                      metadata:
                        type: object
                        required: [name]
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
